FROM ubuntu:22.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      ca-certificates \
      python3 \
      python3-numpy \
      python3-pil && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /work
